fix(build-ios): Use BUILD_DIR instead of CONFIGURATION_BUILD_DIR
Passing `CONFIGURATION_BUILD_DIR` to `xcodebuild` causes
the build errors with projects having `nativescript-plugin-firebase`
when using Xcode 10's new build system similar to the following:
```
Build system information
error: Multiple commands produce '<PbxCp <project-path>/platforms/ios/build/src/core/ext/filters/client_channel/backup_poller.h>':
1) Target 'gRPC-Core' (project 'Pods') has copy command from '<project-path>/platforms/ios/Pods/gRPC-Core/src/core/ext/filters/client_channel/backup_poller.h' to '<project-path>/platforms/ios/build/src/core/ext/filters/client_channel/backup_poller.h'
2) Target 'gRPC-C++' (project 'Pods') has copy command from '<project-path>/platforms/ios/Pods/gRPC-C++/src/core/ext/filters/client_channel/backup_poller.h' to '<project-path>/platforms/ios/build/src/core/ext/filters/client_channel/backup_poller.h'
```